--- 
  - name: Create a directory 
    file:
     path: /opt/tomcat
     state: directory
     
  - name: i want extract my tomcat
    unarchive:
     src: tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
     dest: /home/ubuntu/apache-tomcat-8.5.5.tar.gz
     remote_src: yes 
